[project]
name = "3d-drone-tracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.24",
    "opencv-python>=4.13.0.92",
    "sahi>=0.11",
    "torch>=2.10.0",
    "ultralytics>=8.4",
]
